name: Build

on:
    - push
    - pull_request

jobs:
    build:

        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Dependencies
              run: |
                  sudo apt-get update
                  sudo apt-get install -y lld-12 nasm
                  sudo ln -s /usr/bin/lld-link-12 /usr/bin/lld-link
                  rustup default nightly
                  rustup target add i586-pc-windows-msvc x86_64-pc-windows-msvc
            - name: Compile
              run: cargo run
            - name: Check
              run: cargo run -- check
